---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sprayproxy.yaml
  - route.yaml # only for openshift deployments
  - sprayproxy-rbac.yaml

namespace: sprayproxy

images:
  - name: ko://github.com/redhat-appstudio/sprayproxy
    newName: quay.io/redhat-appstudio/sprayproxy
    newTag: 8546fcd393d79ffbb70b2818df123d549c181fc4

patches:
  - path: add-webhook-secret.yaml
    target:
      name: sprayproxy
      group: apps
      version: v1
      kind: Deployment