---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sprayproxy
  namespace: sprayproxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sprayproxy-kube-rbac-proxy
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sprayproxy-kube-rbac-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sprayproxy-kube-rbac-proxy
subjects:
  - kind: ServiceAccount
    name: sprayproxy
    namespace: sprayproxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sprayproxy-backend-register
rules:
  - nonResourceURLs:
      - "/backends"
    verbs:
      - get
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sprayproxy-backend-register
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sprayproxy-backend-register
subjects:
  - kind: ServiceAccount
    name: sprayproxy
    namespace: sprayproxy